
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npx jest --all --ci

  build:
    runs-on: self-hosted
    needs: test
    strategy:
      matrix:
        node-version: [18.x]
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - run: rm -rf "~/${{ env.REPO_NAME }}"
      - run: cp -r "../${{ env.REPO_NAME }}" ~/
      - run: cp ~/secret_keys "~/${{ env.REPO_NAME }}/.env"
      - name: Build and run
        working-directory: "/home/final-project/${{ env.REPO_NAME }}/"
        run: |
          npm install
          npx prisma migrate deploy
          npm run build
          sudo systemctl restart final-project